Q1 .Demonstrate three different methods for creating identical 2D arrays in NumPyƒ Provide the code for each
method and the final output after each method‚
Ans Here are three different methods for creating identical 2D arrays in NumPy, along with the code for each method and the corresponding output.

### Method 1: Using `numpy.array()`
This method creates a 2D array from a list of lists.

```python
import numpy as np

# Method 1: Using numpy.array()
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Method 1 - Array using np.array():")
print(array_1)
```

**Output:**
```
Method 1 - Array using np.array():
[[1 2 3]
 [4 5 6]]
```

---

### Method 2: Using `numpy.zeros()` and filling it
Here, you create a 2D array filled with zeros and then replace the values.

```python
# Method 2: Using numpy.zeros() and assigning values
array_2 = np.zeros((2, 3), dtype=int)  # Create a 2x3 array filled with zeros
array_2[0, :] = [1, 2, 3]
array_2[1, :] = [4, 5, 6]
print("Method 2 - Array using np.zeros():")
print(array_2)
```

**Output:**
```
Method 2 - Array using np.zeros():
[[1 2 3]
 [4 5 6]]
```

---

### Method 3: Using `numpy.full()`
This method creates a 2D array filled with a specified value.

```python
# Method 3: Using numpy.full() to create a placeholder array, then assigning values
array_3 = np.full((2, 3), 0)  # 2x3 array filled with zeros initially
array_3[0, :] = [1, 2, 3]
array_3[1, :] = [4, 5, 6]
print("Method 3 - Array using np.full():")
print(array_3)
```

**Output:**
```
Method 3 - Array using np.full():
[[1 2 3]
 [4 5 6]]
```

---

### Final Output
All three methods result in the same 2D array:
```
[[1 2 3]
 [4 5 6]]
```



Q2 Using the Numpy function, generate an array of wRR evenly spaced numPers Petween w and wR and Reshape that wD array into a 2D array‚
Ans.To generate an array of evenly spaced numbers between two values \( w \) and \( wR \) using NumPy, and then reshape it into a 2D array, you can use the `numpy.linspace()` function. Below is an example demonstrating this process:

### Example Code

```python
import numpy as np

# Define the values for w, wR, and the number of samples numPers
w = 1  # Starting value
wR = 10  # Ending value
numPers = 9  # Number of samples

# Generate an array of evenly spaced numbers between w and wR
array_1D = np.linspace(w, wR, numPers)

# Reshape the 1D array into a 2D array
# Let's say we want to reshape it into a 3-row array; the number of columns will be adjusted automatically
array_2D = array_1D.reshape(-1, 3)  # Automatically calculate the number of rows based on columns

# Display the results
print("1D Array:")
print(array_1D)
print("\n2D Array:")
print(array_2D)
```

### Explanation:
1. **`np.linspace(w, wR, numPers)`** generates an array of `numPers` evenly spaced numbers between `w` and `wR`.
2. **`reshape(-1, 3)`** reshapes the 1D array into a 2D array with 3 columns, and the number of rows is calculated automatically (using `-1`).

### Output
If you run this code with the defined values of \( w \), \( wR \), and `numPers`, the output will look like this:

**1D Array:**
```
[ 1.   2.   3.   4.   5.   6.   7.   8.   9. ]
```

**2D Array:**
```
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
```



Q3.Explain the following termsg
 The difference in npYarray, npYasarray and npYasanyarrayX
 The difference between Deep copy and shallow copyX
Ans Certainly! Here’s an explanation of the terms you mentioned, including the differences between `np.array`, `np.asarray`, and `np.asanyarray`, as well as the differences between deep copy and shallow copy.

### 1. Difference Between `np.array`, `np.asarray`, and `np.asanyarray`

- **`np.array()`**:
  - **Purpose**: Creates a new NumPy array from a given object (like a list, tuple, etc.).
  - **Behavior**: It always creates a new array regardless of the input type. This means that even if the input is already a NumPy array, `np.array()` will create a copy of that array.
  - **Example**:
    ```python
    import numpy as np

    arr1 = np.array([1, 2, 3])
    arr2 = np.array(arr1)  # Creates a copy
    ```

- **`np.asarray()`**:
  - **Purpose**: Converts an input to an array, but does not create a copy if the input is already an array.
  - **Behavior**: It will return the original array if the input is already a NumPy array, which makes it more memory-efficient in some cases.
  - **Example**:
    ```python
    arr1 = np.array([1, 2, 3])
    arr2 = np.asarray(arr1)  # Does not create a copy, returns the same array
    ```

- **`np.asanyarray()`**:
  - **Purpose**: Similar to `np.asarray()`, but it allows for subclasses of ndarray (like masked arrays) to be returned as arrays.
  - **Behavior**: It does not create a copy if the input is already an ndarray or any subclass of ndarray, but will return the input as it is.
  - **Example**:
    ```python
    arr1 = np.array([1, 2, 3])
    arr2 = np.asanyarray(arr1)  # Returns the same array, regardless of the subclass
    ```

### Summary:
- `np.array()`: Always creates a new array.
- `np.asarray()`: Converts to an array without copying if the input is already an array.
- `np.asanyarray()`: Like `np.asarray()`, but also accepts subclasses of ndarray.

---

### 2. Difference Between Deep Copy and Shallow Copy

- **Shallow Copy**:
  - **Definition**: A shallow copy creates a new object, but it does not create copies of nested objects. Instead, it copies references to the nested objects.
  - **Behavior**: Changes made to nested objects in the original will reflect in the shallow copy, as both share the same reference to the nested objects.
  - **Example**:
    ```python
    import copy

    original = [[1, 2, 3], [4, 5, 6]]
    shallow_copied = copy.copy(original)

    shallow_copied[0][0] = 99  # Modify the nested object
    print(original)  # Output: [[99, 2, 3], [4, 5, 6]]
    ```

- **Deep Copy**:
  - **Definition**: A deep copy creates a new object and recursively creates copies of all nested objects. This means that the new object is completely independent of the original.
  - **Behavior**: Changes made to nested objects in the original will not affect the deep copy.
  - **Example**:
    ```python
    import copy

    original = [[1, 2, 3], [4, 5, 6]]
    deep_copied = copy.deepcopy(original)

    deep_copied[0][0] = 99  # Modify the nested object
    print(original)  # Output: [[1, 2, 3], [4, 5, 6]]
    ```

### Summary:
- **Shallow Copy**: Copies the object but shares references to nested objects.
- **Deep Copy**: Creates a completely independent copy of the object and all nested objects.



Q4 Generate a ‹x‹ array with random floating-point numPers Petween . and 2Rƒ 9hen, round each numPer in the array to 2 decimal placesƒ
Ans.To generate an array with random floating-point numbers between 0 and 2 (as `R` is not defined, I'll assume \( R = 1 \)), and then round each number in the array to 2 decimal places, you can use NumPy as follows:

### Example Code

```python
import numpy as np

# Set the size of the array (e.g., 10)
numPers = 10

# Generate an array of random floating-point numbers between 0 and 2
random_array = np.random.uniform(0, 2, numPers)

# Round each number in the array to 2 decimal places
rounded_array = np.round(random_array, 2)

# Display the results
print("Random Array:")
print(random_array)
print("\nRounded Array:")
print(rounded_array)
```

### Explanation:
1. **`np.random.uniform(0, 2, numPers)`** generates an array of `numPers` random floating-point numbers between 0 and 2.
2. **`np.round(random_array, 2)`** rounds each number in the array to 2 decimal places.

### Output
When you run the code, you might see an output like this (note that the values will be different each time due to randomness):

**Random Array:**
```
[1.23 0.45 1.78 0.98 1.00 0.12 1.56 1.34 0.87 0.66]
```

**Rounded Array:**
```
[1.23 0.45 1.78 0.98 1.   0.12 1.56 1.34 0.87 0.66]
```



Q5  Create a NumPy array with random integers Petween w and wR of shape (., ))ƒ After creating the array
perform the following operations:

 a)Extract all even integers from array.

 b)Extract all odd integers from arrayX

 Ans.To create a NumPy array with random integers between \( w \) and \( wR \) of shape (m, n), and then extract all even and odd integers from that array, you can follow these steps:

### Example Code

```python
import numpy as np

# Define the range values for w and wR
w = 1    # Starting value
wR = 20  # Ending value
shape = (4, 5)  # Shape of the array (4 rows and 5 columns)

# Create a NumPy array with random integers between w and wR
random_array = np.random.randint(w, wR + 1, size=shape)

# Display the generated array
print("Random Integer Array:")
print(random_array)

# a) Extract all even integers from the array
even_integers = random_array[random_array % 2 == 0]
print("\nEven Integers:")
print(even_integers)

# b) Extract all odd integers from the array
odd_integers = random_array[random_array % 2 != 0]
print("\nOdd Integers:")
print(odd_integers)
```

### Explanation:
1. **`np.random.randint(w, wR + 1, size=shape)`** generates a 2D array of random integers between \( w \) (inclusive) and \( wR \) (inclusive). The upper limit is set to \( wR + 1 \) because `randint` generates numbers up to, but not including, the upper bound.
2. **Extracting even integers**: `random_array[random_array % 2 == 0]` selects all integers in the array that are even.
3. **Extracting odd integers**: `random_array[random_array % 2 != 0]` selects all integers in the array that are odd.

### Sample Output
When you run the code, you might see output similar to the following (the values will differ each time due to randomness):

**Random Integer Array:**
```
[[ 2  5 13 14  6]
 [ 8  7 19  1  4]
 [ 3 16 12 11 10]
 [20  9 15 17 18]]
```

**Even Integers:**
```
[ 2 14  6  8  4 16 12 10 20 18]
```

**Odd Integers:**
```
[ 5 13  7 19  1  3 11  9 15 17]
```



Q6.‚ Create a ‹D NumPy array of shape (‹, ‹, ‹) containing random integers Petween w and wRƒ Perform the
following operations:

 a) Find the indices of the maximum values along each depth level (third axis).

 b) Perform elementwise multiplication of between both arrayX
To create a 3D NumPy array of shape \((m, n, p)\) containing random integers between \( w \) and \( wR \), and to perform the specified operations, you can use the following code:

### Example Code

```python
import numpy as np

# Define the range values for w and wR
w = 1    # Starting value
wR = 20  # Ending value
shape = (3, 4, 5)  # Shape of the array (3 layers, 4 rows, 5 columns)

# Create a NumPy array with random integers between w and wR
array_3D = np.random.randint(w, wR + 1, size=shape)

# Display the generated 3D array
print("3D Random Integer Array:")
print(array_3D)

# a) Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array_3D, axis=2)
print("\nIndices of Maximum Values along Each Depth Level (Third Axis):")
print(max_indices)

# b) Create another 3D array for element-wise multiplication
# For demonstration, let's create another random 3D array of the same shape
array_3D_b = np.random.randint(w, wR + 1, size=shape)

# Perform element-wise multiplication between both arrays
elementwise_product = array_3D * array_3D_b

# Display the second random array and the result of the multiplication
print("\nSecond Random Integer Array for Multiplication:")
print(array_3D_b)

print("\nElement-wise Product of Both Arrays:")
print(elementwise_product)
```

### Explanation:
1. **Creating the Array**:
   - **`np.random.randint(w, wR + 1, size=shape)`** generates a 3D array of random integers between \( w \) and \( wR \).
  
2. **Finding Indices of Maximum Values**:
   - **`np.argmax(array_3D, axis=2)`** finds the indices of the maximum values along the third axis (depth level). It returns a 2D array where each element indicates the index of the maximum value for the corresponding layer.

3. **Element-wise Multiplication**:
   - A second random 3D array is created with the same shape.
   - The element-wise multiplication is performed using `array_3D * array_3D_b`, which multiplies the corresponding elements from both arrays.

### Sample Output
When you run the code, the output might look like this (note that the values will differ each time due to randomness):

**3D Random Integer Array:**
```
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20  1  2  3  4]]

 [[ 4  5  6  7  8]
  [ 9 10 11 12 13]
  [14 15 16 17 18]
  [19 20  1  2  3]]]
```

**Indices of Maximum Values along Each Depth Level (Third Axis):**
```
[[4 4 4 4]
 [4 4 4 0]
 [4 4 4 0]]
```

**Second Random Integer Array for Multiplication:**
```
[[[ 2  1  3  5  6]
  [ 8  9  10  1 12]
  [13 14 15 16 17]
  [18 19 20  1  2]]

 [[ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [ 1  2  3  4  5]]

 [[ 8  9 10 11 12]
  [13 14 15 16 17]
  [18 19 20  1  2]
  [ 3  4  5  6  7]]]
```

**Element-wise Product of Both Arrays:**
```
[[[ 2  2  9 20 30]
  [48 63 80  9 120]
  [143 168 195 224 255]
  [288 323 360  20  40]]

 [[30 42 56 72 90]
  [110 132 156 182 210]
  [240 272 306 342 380]
  [20  2  6 12 20]]

 [[32 45 60 77 96]
  [117 140 165 192 221]
  [252 285 320  34  36]
  [57 80 105  12  21]]]
```



Q7  Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and
convert it to a numeric data typeƒ Also display the taPle attriPutes and data types of each column‚
Ans To clean and transform the 'Phone' column in the sample dataset, you'll need to follow these steps:

1. Load the dataset using Pandas.
2. Remove non-numeric characters from the 'Phone' column.
3. Convert the cleaned 'Phone' column to a numeric data type.
4. Display the attributes and data types of each column.

Here’s a complete example using your dataset. I will assume you have the dataset loaded into a Pandas DataFrame.

### Example Code

```python
import pandas as pd

# Load the dataset
file_path = '/mnt/data/People Data.csv'  # Update the file path if necessary
data = pd.read_csv(file_path)

# Display the first few rows of the dataset to inspect the 'Phone' column
print("Original DataFrame:")
print(data.head())

# Clean and transform the 'Phone' column
# Remove non-numeric characters using regex
data['Phone'] = data['Phone'].replace(r'\D+', '', regex=True)

# Convert the 'Phone' column to a numeric data type
data['Phone'] = pd.to_numeric(data['Phone'], errors='coerce')

# Display the updated DataFrame
print("\nUpdated DataFrame:")
print(data.head())

# Display the attributes and data types of each column
print("\nData Types of Each Column:")
print(data.dtypes)

# Optionally, display the attributes of the DataFrame
print("\nDataFrame Attributes:")
print("Shape:", data.shape)
print("Columns:", data.columns.tolist())
print("Index:", data.index)
```

### Explanation:
1. **Loading the Dataset**: The dataset is loaded into a Pandas DataFrame using `pd.read_csv()`.
2. **Cleaning the 'Phone' Column**:
   - `replace(r'\D+', '', regex=True)` removes all non-numeric characters from the 'Phone' column.
3. **Converting to Numeric**:
   - `pd.to_numeric(data['Phone'], errors='coerce')` converts the cleaned 'Phone' column to a numeric data type. If any value cannot be converted, it will be set to `NaN`.
4. **Displaying the DataFrame**:
   - `data.dtypes` shows the data types of each column.
   - Additional attributes such as shape, columns, and index are displayed for further inspection.

### Output
When you run the code, you might see output similar to this (the actual content will vary based on your dataset):

**Original DataFrame:**
```
    Name          Phone
0  John Doe     (123) 456-7890
1  Jane Smith   +1-800-555-0123
2  Alice Jones   555.0123
3  Bob Brown     123-456-7890
4  Charlie Black 1234567890
```

**Updated DataFrame:**
```
    Name          Phone
0  John Doe     1234567890
1  Jane Smith   18005550123
2  Alice Jones   5550123
3  Bob Brown     1234567890
4  Charlie Black 1234567890
```

**Data Types of Each Column:**
```
Name      object
Phone    float64
dtype: object
```

**DataFrame Attributes:**
```
Shape: (5, 2)
Columns: ['Name', 'Phone']
Index: RangeIndex(start=0, stop=5, step=1)
```

Feel free to run the code, and let me know if you have any questions or need further modifications!

Q8.Perform the following tas\s using people dataset:

 a) Read the 'dataYcsv' file using pandas, skipping the first 50 rows.

 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 c) Display the first 10 rows of the filtered dataset.

 d) Extract the ‘Salary’' column as a Series and display its last 5 valuesX
 To perform the specified tasks using the People dataset, you can follow these steps with Pandas. Here’s the complete code to read the dataset, filter the required columns, and extract the relevant information.

### Example Code

```python
import pandas as pd

# a) Read the 'People Data.csv' file using pandas, skipping the first 50 rows.
file_path = '/mnt/data/People Data.csv'  # Update the file path if necessary
data = pd.read_csv(file_path, skiprows=50)

# b) Only read the columns: 'Last Name', 'Gender', 'Email', 'Phone', and 'Salary'.
filtered_columns = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']
filtered_data = data[filtered_columns]

# c) Display the first 10 rows of the filtered dataset.
print("First 10 rows of the filtered dataset:")
print(filtered_data.head(10))

# d) Extract the 'Salary' column as a Series and display its last 5 values.
salary_series = filtered_data['Salary']
print("\nLast 5 values of the 'Salary' column:")
print(salary_series.tail(5))
```

### Explanation:
1. **Reading the Dataset**:
   - The `pd.read_csv(file_path, skiprows=50)` function reads the CSV file, skipping the first 50 rows. Adjust the `file_path` as necessary.
  
2. **Filtering Columns**:
   - `filtered_data = data[filtered_columns]` selects only the specified columns from the DataFrame.

3. **Displaying the First 10 Rows**:
   - `filtered_data.head(10)` displays the first 10 rows of the filtered DataFrame.

4. **Extracting the 'Salary' Column**:
   - `salary_series = filtered_data['Salary']` extracts the 'Salary' column as a Series.
   - `salary_series.tail(5)` displays the last 5 values of the 'Salary' column.

### Output
When you run the code, the output might look similar to this (the actual content will vary based on your dataset):

**First 10 rows of the filtered dataset:**
```
     Last Name  Gender              Email          Phone   Salary
0    Doe        Male    john.doe@example.com  123-456-7890  50000
1    Smith      Female  jane.smith@example.com 234-567-8901  60000
2    Jones      Male    alice.jones@example.com 345-678-9012  70000
3    Brown      Female  bob.brown@example.com 456-789-0123  80000
4    Black      Male    charlie.black@example.com 567-890-1234  55000
5    White      Female  emily.white@example.com 678-901-2345  65000
6    Green      Male    frank.green@example.com 789-012-3456  72000
7    Grey       Female  grace.grey@example.com 890-123-4567  59000
8    Yellow     Male    harry.yellow@example.com 901-234-5678  63000
9    Blue       Female  irene.blue@example.com 012-345-6789  58000
```

**Last 5 values of the 'Salary' column:**
```
5    65000
6    72000
7    59000
8    63000
9    58000
Name: Salary, dtype: int64
```


Q9.Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Du\e',
'Gender' column contains the word Female and ‘Nalary’ should Pe less than _.RRR‚
Ans.To filter and select rows from the People dataset where the **'Last Name'** column contains the name **'Duke'**, the **'Gender'** column contains the word **'Female'**, and the **'Salary'** is less than a specified value (let's assume \( R = 60000 \)), you can use the following code:

### Example Code

```python
import pandas as pd

# Load the dataset
file_path = '/mnt/data/People Data.csv'  # Update the file path if necessary
data = pd.read_csv(file_path)

# Filter and select rows based on the specified conditions
filtered_data = data[
    (data['Last Name'].str.contains('Duke', case=False, na=False)) &
    (data['Gender'].str.contains('Female', case=False, na=False)) &
    (data['Salary'] < 60000)  # Adjust the threshold value as needed
]

# Display the filtered dataset
print("Filtered Rows:")
print(filtered_data)
```

### Explanation:
1. **Loading the Dataset**:
   - The dataset is loaded into a Pandas DataFrame using `pd.read_csv()`.
  
2. **Filtering Conditions**:
   - **`data['Last Name'].str.contains('Duke', case=False, na=False)`** checks if the 'Last Name' contains 'Duke', ignoring case and avoiding NaN values.
   - **`data['Gender'].str.contains('Female', case=False, na=False)`** checks if the 'Gender' column contains 'Female', also ignoring case.
   - **`data['Salary'] < 60000`** checks if the 'Salary' is less than 60000.

3. **Combining Conditions**:
   - The conditions are combined using the `&` operator, which ensures that all conditions must be satisfied for a row to be included in the filtered DataFrame.

4. **Displaying the Filtered Dataset**:
   - The filtered DataFrame is printed out.

### Output
When you run the code, the output might look like this (the actual content will vary based on your dataset):

**Filtered Rows:**
```
    Last Name  Gender              Email           Phone  Salary
10   Duke       Female  eliza.duke@example.com  123-456-7890  50000
11   Duke       Female  anna.duke@example.com   987-654-3210  55000
```



Q10.Create a 7*. Dataframe in Pandas using a series generated from ‹. random integers Petween w to )?
Ans.To create a 7x7 DataFrame in Pandas using a series generated from random integers between a specified range \( w \) to \( wR \), you can follow the steps outlined below. For this example, I will assume that \( w = 1 \) and \( wR = 100 \).

### Example Code

```python
import pandas as pd
import numpy as np

# Define the range for random integers
w = 1    # Starting value
wR = 100 # Ending value

# Generate a Series of random integers
random_series = np.random.randint(w, wR + 1, size=49)  # 7x7 = 49 elements

# Create a 7x7 DataFrame from the random Series
random_dataframe = pd.DataFrame(random_series.reshape(7, 7), columns=[f'Column {i+1}' for i in range(7)])

# Display the generated DataFrame
print("7x7 DataFrame:")
print(random_dataframe)
```

### Explanation:
1. **Defining the Range**:
   - The values of \( w \) and \( wR \) are defined for generating random integers.

2. **Generating Random Integers**:
   - **`np.random.randint(w, wR + 1, size=49)`** generates 49 random integers between \( w \) and \( wR \).

3. **Creating a DataFrame**:
   - The generated random integers are reshaped into a 7x7 format using `.reshape(7, 7)` and passed to `pd.DataFrame()` to create the DataFrame.
   - Column names are created dynamically using a list comprehension.

4. **Displaying the DataFrame**:
   - The generated DataFrame is printed out.

### Output
When you run the code, the output will look something like this (the actual values will differ each time due to randomness):

**7x7 DataFrame:**
```
   Column 1  Column 2  Column 3  Column 4  Column 5  Column 6  Column 7
0        34        78        45        67        12        90        21
1        56        39        85        23        67        11        44
2        70        81        58        26        75        30        19
3        98        14        22        33        48        49        71
4        84        92        60        37        53        76        15
5        29        10        88        99        72        18        25
6        66        55        74        81        95        13        62
```


Q11.Create two different Series, each of length 50, with the following criteria:

a) The first Series should contain random numbers ranging from 10 to 50.

b) The second Series should contain random numbers ranging from 100 to 1000.

c) Create a DataFrame by 'oining these Series by column, and, change the names of the columns to 'col1', 'col2',
etc&
Ans.To create two different Series of length 50 with the specified criteria and then combine them into a DataFrame with renamed columns, you can use the following code:

### Example Code

```python
import pandas as pd
import numpy as np

# a) Create the first Series with random numbers ranging from 10 to 50
series1 = np.random.randint(10, 51, size=50)

# b) Create the second Series with random numbers ranging from 100 to 1000
series2 = np.random.randint(100, 1001, size=50)

# c) Create a DataFrame by joining these Series by column
df = pd.DataFrame({
    'col1': series1,
    'col2': series2
})

# Display the resulting DataFrame
print("DataFrame with two Series:")
print(df)
```

### Explanation:
1. **Creating the First Series**:
   - **`np.random.randint(10, 51, size=50)`** generates 50 random integers between 10 (inclusive) and 51 (exclusive).
  
2. **Creating the Second Series**:
   - **`np.random.randint(100, 1001, size=50)`** generates 50 random integers between 100 (inclusive) and 1000 (inclusive).

3. **Creating the DataFrame**:
   - A DataFrame is created by passing a dictionary to `pd.DataFrame()` where the keys represent the new column names ('col1' and 'col2') and the values are the Series created earlier.

4. **Displaying the DataFrame**:
   - The resulting DataFrame is printed to the console.

### Output
When you run the code, the output will look something like this (the actual values will differ each time due to randomness):

**DataFrame with two Series:**
```
    col1  col2
0     27   648
1     38   532
2     14   850
3     46   125
4     10   769
5     29   215
6     40   430
7     35   989
8     19   375
9     43   302
10    23   174
11    15   916
12    50   303
13    45   415
14    37   928
15    34   108
16    30   610
17    20   906
18    39   572
19    49   276
20    44   919
21    12   426
22    16   865
23    25   717
24    18   930
25    21   838
26    33   647
27    11   352
28    26   118
29    32   484
30    24   652
31    47   972
32    36   546
33    48   713
34    41   504
35    42   303
36    13   492
37    28   227
38    17   203
39    15   547
40    22   383
41    39   651
42    10   670
43    31   160
44    29   490
45    45   747
46    36   290
47    11   225
48    12   498
49    50   187
```



Q12.Perform the following operations using people data set:

a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

b) Delete the rows containing any missing values.

d) Print the final outut also&
To perform the specified operations on the People dataset—deleting certain columns, removing rows with missing values, and printing the final output—you can use the following code:

### Example Code

```python
import pandas as pd

# Load the dataset
file_path = '/mnt/data/People Data.csv'  # Update the file path if necessary
data = pd.read_csv(file_path)

# a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.
columns_to_delete = ['Email', 'Phone', 'Date of birth']
data = data.drop(columns=columns_to_delete)

# b) Delete the rows containing any missing values.
data = data.dropna()

# d) Print the final output
print("Final DataFrame after deleting specified columns and rows with missing values:")
print(data)
```

### Explanation:
1. **Loading the Dataset**:
   - The dataset is loaded into a Pandas DataFrame using `pd.read_csv()`.

2. **Deleting Specified Columns**:
   - `data.drop(columns=columns_to_delete)` removes the 'Email', 'Phone', and 'Date of birth' columns from the DataFrame.

3. **Deleting Rows with Missing Values**:
   - `data.dropna()` removes any rows that contain missing values in any column.

4. **Printing the Final Output**:
   - The resulting DataFrame is printed to the console.

### Output
When you run the code, the output will look something like this (the actual content will vary based on your dataset):

**Final DataFrame after deleting specified columns and rows with missing values:**
```
   Last Name  Gender  Salary
0       Doe    Male   50000
1     Smith  Female   60000
2     Jones    Male   70000
3     Brown  Female   80000
4     Black    Male   55000
5     White  Female   65000
```



Q13.Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the
following tasks using Matplotlib and NumPy:

a) Create a scatter lot using x and y, setting the color of the oints to red and the marker style to 'o'.

b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.

c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

e) Set the title of the lot as 'Advanced Scatter Plot of Random Values'.

f) Dislay a legend for the scatter lot, the horizontal line, and the vertical line.
Ans.To create a scatter plot with the specified requirements using NumPy and Matplotlib, you can follow the steps outlined below. This code generates two arrays of random float values and creates a scatter plot with horizontal and vertical lines, along with appropriate labels and a legend.

### Example Code

```python
import numpy as np
import matplotlib.pyplot as plt

# Create two NumPy arrays with 100 random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# a) Create a scatter plot
plt.scatter(x, y, color='red', marker='o', label='Random Points')

# b) Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# c) Add a vertical line at x = 0.5
plt.axvline(x=0.5, color='green', linestyle=':', label='x = 0.5')

# d) Label the x-axis and y-axis
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# e) Set the title of the plot
plt.title('Advanced Scatter Plot of Random Values')

# f) Display a legend
plt.legend()

# Show the plot
plt.show()
```

### Explanation:
1. **Creating Random Arrays**:
   - `x` and `y` are created as NumPy arrays with 100 random float values between 0 and 1 using `np.random.rand(100)`.

2. **Scatter Plot**:
   - The `plt.scatter()` function creates a scatter plot with red points, using 'o' as the marker style.

3. **Horizontal Line**:
   - The `plt.axhline()` function adds a horizontal dashed line at \( y = 0.5 \) with a label.

4. **Vertical Line**:
   - The `plt.axvline()` function adds a vertical dotted line at \( x = 0.5 \) with a label.

5. **Axis Labels and Title**:
   - `plt.xlabel()` and `plt.ylabel()` label the axes, while `plt.title()` sets the title of the plot.

6. **Legend**:
   - `plt.legend()` displays a legend for the scatter plot, horizontal line, and vertical line.

7. **Displaying the Plot**:
   - Finally, `plt.show()` renders the plot.

### Output
When you run the code, you will see a scatter plot similar to this (the actual points will vary due to randomness):

- **Red points** representing the random values in the scatter plot.
- A **dashed blue line** at \( y = 0.5 \).
- A **dotted green line** at \( x = 0.5 \).
- Labels for the axes, a title, and a legend showing the descriptions of each element.



Q14. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and
Perform the following tasks using Matplotlib:
K§g Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following
tasks using Matplotlib:
KÃg Set the title of the plot as 'Histogram with PDF Overlay'.
Kçg Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the
origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.
a) Plot the 'Temerature' and 'Humidity' on the same lot with different y-axes (left y-axis for 'Temerature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the lot as 'Temerature and Humidity Over Time'.
Ans.To create a time-series dataset and perform the specified tasks using Pandas and Matplotlib, as well as include a histogram and a scatter plot with Seaborn, you can follow the code example below:

### Example Code

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Create a time-series dataset
date_range = pd.date_range(start='2023-01-01', periods=100, freq='D')
temperature = np.random.normal(loc=20, scale=5, size=len(date_range))  # Normal distribution for temperature
humidity = np.random.normal(loc=50, scale=10, size=len(date_range))     # Normal distribution for humidity

# Create DataFrame
weather_data = pd.DataFrame({'Date': date_range, 'Temperature': temperature, 'Humidity': humidity})

# a) Plot Temperature and Humidity on the same plot with different y-axes
fig, ax1 = plt.subplots()

# Plot Temperature
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature', color='tab:red')
ax1.plot(weather_data['Date'], weather_data['Temperature'], color='tab:red', label='Temperature')
ax1.tick_params(axis='y', labelcolor='tab:red')

# Create a second y-axis for Humidity
ax2 = ax1.twinx()
ax2.set_ylabel('Humidity', color='tab:blue')
ax2.plot(weather_data['Date'], weather_data['Humidity'], color='tab:blue', label='Humidity')
ax2.tick_params(axis='y', labelcolor='tab:blue')

# Set the title of the plot
plt.title('Temperature and Humidity Over Time')
plt.show()

# K§g Create a NumPy array containing 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)

# Set the title of the histogram plot
plt.figure(figsize=(10, 6))
plt.hist(data, bins=30, density=True, alpha=0.6, color='g')

# Overlay the PDF
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = np.exp(-x**2 / 2) / np.sqrt(2 * np.pi)
plt.plot(x, p, 'k', linewidth=2)
plt.title('Histogram with PDF Overlay')
plt.xlabel('Value')
plt.ylabel('Density')
plt.show()

# KÃg Create a Seaborn scatter plot of two random arrays
x_scatter = np.random.rand(100)
y_scatter = np.random.rand(100)

# Determine the quadrants and color points based on their position
colors = ['red' if (x >= 0.5 and y >= 0.5) else 'blue' if (x < 0.5 and y >= 0.5) else 'green' if (x < 0.5 and y < 0.5) else 'orange' for x, y in zip(x_scatter, y_scatter)]

# Create the scatter plot
plt.figure(figsize=(10, 6))
scatter = plt.scatter(x_scatter, y_scatter, c=colors)
plt.title('Quadrant-wise Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Add legend
red_patch = plt.Line2D([0], [0], marker='o', color='w', label='Quadrant I', markerfacecolor='red', markersize=10)
blue_patch = plt.Line2D([0], [0], marker='o', color='w', label='Quadrant II', markerfacecolor='blue', markersize=10)
green_patch = plt.Line2D([0], [0], marker='o', color='w', label='Quadrant III', markerfacecolor='green', markersize=10)
orange_patch = plt.Line2D([0], [0], marker='o', color='w', label='Quadrant IV', markerfacecolor='orange', markersize=10)
plt.legend(handles=[red_patch, blue_patch, green_patch, orange_patch])
plt.show()
```

### Explanation of Each Part:

1. **Creating the Time-Series Dataset**:
   - A date range is created using `pd.date_range()`, and random values for temperature and humidity are generated from a normal distribution using `np.random.normal()`.
   - A DataFrame called `weather_data` is created with columns 'Date', 'Temperature', and 'Humidity'.

2. **Plotting Temperature and Humidity**:
   - The temperature is plotted on the left y-axis, and humidity is plotted on the right y-axis using `ax1.twinx()`.
   - Labels and titles are added accordingly.

3. **Creating a Histogram with PDF Overlay**:
   - A NumPy array containing 1000 samples from a normal distribution is created.
   - A histogram is plotted using `plt.hist()`, and a probability density function (PDF) is overlaid on the histogram.

4. **Creating a Quadrant-wise Scatter Plot**:
   - Two random arrays are created for the scatter plot.
   - Colors are assigned based on which quadrant the points fall into (determined by their position relative to 0.5).
   - A scatter plot is created using Seaborn with colors representing different quadrants, and a legend is included.

### Output
When you run the code, you will see:
- A time-series plot for temperature and humidity.
- A histogram with a PDF overlay.
- A scatter plot with points colored according to their quadrants.



Q15. Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following
tasks using Matplotlib:
KÃg Set the title of the plot as 'Histogram with PDF Overlay'.
Kçg Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the
origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.
a) Plot the 'Temerature' and 'Humidity' on the same lot with different y-axes (left y-axis for 'Temerature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the lot as 'Temerature and Humidity Over Time'.
a) Plot a histogram of the data with 30 bins.

b) Overlay a line lot reresenting the normal distribution's robability density function (PDF).

c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

d) Set the title of the lot as 'Histogram with PDF Overlay'.
Ans.Below is a complete Python code snippet that fulfills all the tasks you specified, including creating a histogram with a PDF overlay, a Seaborn scatter plot of two random arrays, and a time-series plot of temperature and humidity.

### Example Code

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm

# Step 1: Create a NumPy array with 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)

# Step 2: Create a histogram of the data with 30 bins and overlay the PDF
plt.figure(figsize=(12, 6))
plt.hist(data, bins=30, density=True, alpha=0.6, color='g', label='Histogram')

# Overlay the PDF
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, loc=0, scale=1)  # PDF of the normal distribution
plt.plot(x, p, 'k', linewidth=2, label='PDF')
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')
plt.legend()
plt.show()

# Step 3: Create two random arrays for the scatter plot
x_scatter = np.random.rand(100)
y_scatter = np.random.rand(100)

# Determine the quadrants and color points based on their position
colors = ['red' if (x >= 0.5 and y >= 0.5) else
          'blue' if (x < 0.5 and y >= 0.5) else
          'green' if (x < 0.5 and y < 0.5) else
          'orange' for x, y in zip(x_scatter, y_scatter)]

# Create the scatter plot
plt.figure(figsize=(10, 6))
scatter = plt.scatter(x_scatter, y_scatter, c=colors, label='Points by Quadrant')
plt.title('Quadrant-wise Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Add legend
plt.legend(['Quadrant I', 'Quadrant II', 'Quadrant III', 'Quadrant IV'], loc='upper left')
plt.show()

# Step 4: Create a time-series dataset for Temperature and Humidity
date_range = pd.date_range(start='2023-01-01', periods=100, freq='D')
temperature = np.random.normal(loc=20, scale=5, size=len(date_range))  # Normal distribution for temperature
humidity = np.random.normal(loc=50, scale=10, size=len(date_range))     # Normal distribution for humidity

# Create DataFrame
weather_data = pd.DataFrame({'Date': date_range, 'Temperature': temperature, 'Humidity': humidity})

# Plot Temperature and Humidity on the same plot with different y-axes
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot Temperature
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature', color='tab:red')
ax1.plot(weather_data['Date'], weather_data['Temperature'], color='tab:red', label='Temperature')
ax1.tick_params(axis='y', labelcolor='tab:red')

# Create a second y-axis for Humidity
ax2 = ax1.twinx()
ax2.set_ylabel('Humidity', color='tab:blue')
ax2.plot(weather_data['Date'], weather_data['Humidity'], color='tab:blue', label='Humidity')
ax2.tick_params(axis='y', labelcolor='tab:blue')

# Set the title of the plot
plt.title('Temperature and Humidity Over Time')
plt.show()
```

### Explanation of Each Part:

1. **Creating Normal Distribution Data**:
   - A NumPy array named `data` is created with 1000 samples drawn from a normal distribution with mean 0 and standard deviation 1.

2. **Creating Histogram with PDF Overlay**:
   - A histogram of the data is plotted with 30 bins using `plt.hist()`.
   - The PDF of the normal distribution is computed and overlaid on the histogram.

3. **Creating Quadrant-wise Scatter Plot**:
   - Two random arrays, `x_scatter` and `y_scatter`, are created for the scatter plot.
   - Points are colored based on their quadrant location (using conditional logic) relative to the origin.
   - A scatter plot is generated using Matplotlib with appropriate labels and a legend.

4. **Creating Time-Series Data for Temperature and Humidity**:
   - A date range is generated, and two random normal distributions for temperature and humidity are created.
   - A DataFrame is created with the date, temperature, and humidity.
   - A plot is created with temperature on the left y-axis and humidity on the right y-axis, with appropriate titles and labels.

### Output
When you run the code, you will see:
- A histogram with a PDF overlay.
- A scatter plot of points colored by quadrant.
- A time-series plot of temperature and humidity over time.



Q16.Set the title of the plot as 'Histogram with PDF Overlay'.
Ans.To set the title of the plot as 'Histogram with PDF Overlay', you can include the following line in the code where you create the histogram plot. Below is the complete code snippet that includes this title setting.

### Updated Example Code

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm

# Step 1: Create a NumPy array with 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)

# Step 2: Create a histogram of the data with 30 bins and overlay the PDF
plt.figure(figsize=(12, 6))
plt.hist(data, bins=30, density=True, alpha=0.6, color='g', label='Histogram')

# Overlay the PDF
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, loc=0, scale=1)  # PDF of the normal distribution
plt.plot(x, p, 'k', linewidth=2, label='PDF')

# Label the axes and set the title
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')  # Setting the title here
plt.legend()
plt.show()

# Step 3: Create two random arrays for the scatter plot
x_scatter = np.random.rand(100)
y_scatter = np.random.rand(100)

# Determine the quadrants and color points based on their position
colors = ['red' if (x >= 0.5 and y >= 0.5) else
          'blue' if (x < 0.5 and y >= 0.5) else
          'green' if (x < 0.5 and y < 0.5) else
          'orange' for x, y in zip(x_scatter, y_scatter)]

# Create the scatter plot
plt.figure(figsize=(10, 6))
scatter = plt.scatter(x_scatter, y_scatter, c=colors, label='Points by Quadrant')
plt.title('Quadrant-wise Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Add legend
plt.legend(['Quadrant I', 'Quadrant II', 'Quadrant III', 'Quadrant IV'], loc='upper left')
plt.show()

# Step 4: Create a time-series dataset for Temperature and Humidity
date_range = pd.date_range(start='2023-01-01', periods=100, freq='D')
temperature = np.random.normal(loc=20, scale=5, size=len(date_range))  # Normal distribution for temperature
humidity = np.random.normal(loc=50, scale=10, size=len(date_range))     # Normal distribution for humidity

# Create DataFrame
weather_data = pd.DataFrame({'Date': date_range, 'Temperature': temperature, 'Humidity': humidity})

# Plot Temperature and Humidity on the same plot with different y-axes
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot Temperature
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature', color='tab:red')
ax1.plot(weather_data['Date'], weather_data['Temperature'], color='tab:red', label='Temperature')
ax1.tick_params(axis='y', labelcolor='tab:red')

# Create a second y-axis for Humidity
ax2 = ax1.twinx()
ax2.set_ylabel('Humidity', color='tab:blue')
ax2.plot(weather_data['Date'], weather_data['Humidity'], color='tab:blue', label='Humidity')
ax2.tick_params(axis='y', labelcolor='tab:blue')

# Set the title of the plot
plt.title('Temperature and Humidity Over Time')
plt.show()
```

### Key Changes
- The title of the histogram plot is explicitly set using `plt.title('Histogram with PDF Overlay')`.



Q17.Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the
origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.
Ans.To create a Seaborn scatter plot of two random arrays, color the points based on their position relative to the origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot', you can use the following code snippet:

### Code Example

```python
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Create two random arrays
x_scatter = np.random.rand(100) * 10  # Random numbers between 0 and 10
y_scatter = np.random.rand(100) * 10  # Random numbers between 0 and 10

# Step 2: Create a DataFrame
data = pd.DataFrame({'X': x_scatter, 'Y': y_scatter})

# Step 3: Create a column for quadrant colors
def get_quadrant(row):
    if row['X'] >= 5 and row['Y'] >= 5:
        return 'Quadrant I (Red)'
    elif row['X'] < 5 and row['Y'] >= 5:
        return 'Quadrant II (Blue)'
    elif row['X'] < 5 and row['Y'] < 5:
        return 'Quadrant III (Green)'
    else:
        return 'Quadrant IV (Orange)'

data['Quadrant'] = data.apply(get_quadrant, axis=1)

# Step 4: Create a Seaborn scatter plot
plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='X', y='Y', hue='Quadrant', palette={'Quadrant I (Red)': 'red',
                                                                 'Quadrant II (Blue)': 'blue',
                                                                 'Quadrant III (Green)': 'green',
                                                                 'Quadrant IV (Orange)': 'orange'})

# Step 5: Customize the plot
plt.title('Quadrant-wise Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend(title='Quadrants')
plt.grid(True)
plt.show()
```

### Explanation of the Code:
1. **Creating Random Arrays**:
   - Two random arrays, `x_scatter` and `y_scatter`, are generated with values between 0 and 10.

2. **Creating a DataFrame**:
   - A DataFrame named `data` is created containing the random arrays.

3. **Determining Quadrants**:
   - A new column named `Quadrant` is added to the DataFrame based on the values of `X` and `Y`. The function `get_quadrant` assigns a label for each quadrant.

4. **Creating the Scatter Plot**:
   - A Seaborn scatter plot is generated using `sns.scatterplot()`, with points colored according to their assigned quadrant. A custom color palette is defined.

5. **Customizing the Plot**:
   - The title, x-axis label, y-axis label, and legend are added for better clarity.



Q18.8 With Bo+eh, plot a line chart of a sine wave function, add rid lines, label the axes, and set the title as 'Sine
Wave Function'
Ans.To plot a line chart of a sine wave function using Bokeh, add grid lines, label the axes, and set the title as 'Sine Wave Function', you can use the following code.

### Code Example

```python
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
import numpy as np

# Step 1: Prepare the data
x = np.linspace(0, 2 * np.pi, 100)  # x values from 0 to 2π
y = np.sin(x)  # y values as the sine of x

# Step 2: Create a Bokeh figure
p = figure(title='Sine Wave Function', x_axis_label='X-axis', y_axis_label='Y-axis',
           width=800, height=400)

# Step 3: Add grid lines
p.grid.grid_line_color = 'grey'
p.grid.grid_line_alpha = 0.5

# Step 4: Add the sine wave line
p.line(x, y, legend_label='sin(x)', line_width=2, color='blue')

# Step 5: Show the plot
output_notebook()  # Use this line to display in Jupyter Notebook. Remove if running in a script.
show(p)
```

### Explanation of the Code:
1. **Prepare the Data**:
   - `x` values are generated using `numpy.linspace()` to create 100 points between 0 and \(2\pi\).
   - `y` values are calculated as the sine of `x`.

2. **Create a Bokeh Figure**:
   - A Bokeh figure is created with titles and axis labels.

3. **Add Grid Lines**:
   - The grid lines are customized with a grey color and adjusted transparency using `grid_line_alpha`.

4. **Add the Sine Wave Line**:
   - The sine wave is added to the plot using `p.line()`, with a specified legend label, line width, and color.

5. **Show the Plot**:
   - The `show(p)` function displays the plot. The `output_notebook()` line is used for Jupyter Notebook environments. If you're running this in a standalone script, you can remove that line.



Q19.Usin Bo+eh, enerate a bar chart of randomly enerated cateorical data, color bars based on their
values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Cateorical
Bar Chart'
Ans.To generate a bar chart of randomly generated categorical data using Bokeh, with color-coded bars based on their values, hover tooltips displaying exact values, labeled axes, and the title 'Random Categorical Bar Chart', you can use the following code:

### Code Example

```python
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.models import ColumnDataSource, HoverTool
import numpy as np
import pandas as pd

# Step 1: Prepare random categorical data
categories = ['A', 'B', 'C', 'D', 'E']  # Define categories
values = np.random.randint(10, 100, size=len(categories))  # Random values between 10 and 100

# Step 2: Create a DataFrame and a ColumnDataSource
data = pd.DataFrame({'Category': categories, 'Value': values})
source = ColumnDataSource(data=data)

# Step 3: Create a Bokeh figure
p = figure(x_range=categories, title='Random Categorical Bar Chart',
           x_axis_label='Categories', y_axis_label='Values',
           plot_height=400, toolbar_location=None)

# Step 4: Add color to bars based on values
color_mapping = ['red' if value < 30 else 'yellow' if value < 60 else 'green' for value in values]

# Step 5: Create bars
p.vbar(x='Category', top='Value', source=source, width=0.9, color=color_mapping, legend_field='Category')

# Step 6: Add hover tooltips
hover = HoverTool()
hover.tooltips = [("Category", "@Category"), ("Value", "@Value")]
p.add_tools(hover)

# Step 7: Customize the plot
p.legend.title = "Categories"
p.xgrid.grid_line_color = None
p.y_range.start = 0
p.y_range.end = max(values) + 10

# Step 8: Show the plot
output_notebook()  # Use this line to display in Jupyter Notebook. Remove if running in a script.
show(p)
```

### Explanation of the Code:
1. **Prepare Random Categorical Data**:
   - Define a list of categories and generate random integer values between 10 and 100 for these categories.

2. **Create a DataFrame and ColumnDataSource**:
   - A DataFrame is created from the categories and values, and a `ColumnDataSource` is used to feed the data to the Bokeh plot.

3. **Create a Bokeh Figure**:
   - A Bokeh figure is initialized with specified x-range, title, and axis labels.

4. **Add Color to Bars**:
   - Bars are colored based on their values using a list comprehension that assigns colors (red, yellow, green) depending on the value.

5. **Create Bars**:
   - Vertical bars are added to the plot using `p.vbar()` with specified colors.

6. **Add Hover Tooltips**:
   - A `HoverTool` is added to display the category and value when hovering over the bars.

7. **Customize the Plot**:
   - The legend title is set, grid lines are adjusted, and the y-axis range is configured.

8. **Show the Plot**:
   - The `show(p)` function displays the plot. The `output_notebook()` line is used for Jupyter Notebook environments; you can remove it if running in a standalone script.


Q20.Usin Plotly, create a basic line plot of a randomly enerated dataset, label the axes, and set the title as
'Simple Line Plot'
AnsTo create a basic line plot of a randomly generated dataset using Plotly, you can use the following code. This example will generate random data and display it in a line plot with labeled axes and a title.

### Code Example

```python
import plotly.graph_objects as go
import numpy as np

# Step 1: Generate random data
x = np.linspace(0, 10, 100)  # x values from 0 to 10
y = np.random.rand(100) * 10  # y values as random numbers between 0 and 10

# Step 2: Create a line plot
fig = go.Figure()

# Step 3: Add a line trace
fig.add_trace(go.Scatter(x=x, y=y, mode='lines', name='Random Data', line=dict(color='blue')))

# Step 4: Label the axes and set the title
fig.update_layout(title='Simple Line Plot',
                  xaxis_title='X-axis',
                  yaxis_title='Y-axis')

# Step 5: Show the plot
fig.show()
```

### Explanation of the Code:
1. **Generate Random Data**:
   - `x` is generated using `np.linspace()` to create 100 points between 0 and 10.
   - `y` values are generated as random numbers multiplied by 10.

2. **Create a Line Plot**:
   - A Plotly figure is created with `go.Figure()`.

3. **Add a Line Trace**:
   - A line trace is added to the figure using `go.Scatter()`, with specified x and y data. The `mode` is set to `'lines'` to create a line plot, and the line color is specified.

4. **Label the Axes and Set the Title**:
   - The x-axis and y-axis are labeled, and the plot title is set using `update_layout()`.

5. **Show the Plot**:
   - The plot is displayed using `fig.show()`.



Q21.Usin Plotly, create an interactive pie chart of randomly enerated data, add labels and percentaes, set
the title as 'Interactive Pie Chart'.
Ans To create an interactive pie chart of randomly generated data using Plotly, you can use the following code. This example generates random data for the pie chart and adds labels and percentages, with the title set as 'Interactive Pie Chart'.

### Code Example

```python
import plotly.graph_objects as go
import numpy as np

# Step 1: Generate random data
labels = ['Category A', 'Category B', 'Category C', 'Category D', 'Category E']  # Define labels
values = np.random.randint(10, 100, size=len(labels))  # Random values between 10 and 100

# Step 2: Create a pie chart
fig = go.Figure(data=[go.Pie(labels=labels, values=values,
                               textinfo='label+percent',  # Show labels and percentages
                               hole=0.3)])  # Optional: create a donut chart by setting hole size

# Step 3: Set the title
fig.update_layout(title='Interactive Pie Chart')

# Step 4: Show the plot
fig.show()
```

### Explanation of the Code:
1. **Generate Random Data**:
   - A list of labels representing different categories is defined.
   - Random values are generated for these categories using `np.random.randint()` to create integers between 10 and 100.

2. **Create a Pie Chart**:
   - A Plotly figure is created using `go.Figure()`, and a pie chart is added with `go.Pie()`. The `textinfo` parameter is set to `'label+percent'` to display both labels and percentages on the pie slices. The `hole` parameter is set to 0.3 to create a donut chart; you can remove this parameter if you want a standard pie chart.

3. **Set the Title**:
   - The title of the chart is set using `update_layout()`.

4. **Show the Plot**:
   - The pie chart is displayed using `fig.show()`.

